### ISSUE TITLE
Thread panic 'Integer too large'

### ISSUE THREAD

**Issue by ajeroth** [xforce/eve-echoes-tools#10]
[error.log](https://github.com/xforce/eve-echoes-tools/files/5522739/error.log)
Hello again,
Thanks for your help on the previous issue.  I'm attempting another round and I got another error . . .

This time there is a panicked thread with a error about an integer being too large. I have attached a log generated with RUST_BACKTRACE=full.

I went and recompiled fsd2json, and didn't recieve any errors at compile time.

Thanks again for all your time and help!  Not to mention building this in the first place :)

**Comment by xforce** [comment]
Yep, I noticed while I was working on providing better support for 'overlaying' patches on top of existing files.
I have a local fix which I will push later today.

**Comment by xforce** [comment]
Fixed in master.
Also added preliminary support to handle patches to `dump_static_data.py`
