### ISSUE TITLE
Translation index

### ISSUE THREAD

**Issue by bilhackmac** [xforce/eve-echoes-tools#3]
Hi.

First thanks for this tools, it's really awesome.

Maybe I miss something but I don't find a way to use `res/staticdata/gettext/msg_index/index.json` (once extracted).
Values match locales `res/staticdata/gettext/<locale>/*` but keys doesn't match any objects id.

Have you any idea ?

**Comment by xforce** [comment]
Take a look at the included [text_lookup.py](https://github.com/xforce/eve-echoes-tools/blob/main/scripts/text_lookup.py)

Basically translations work based on a hash of the chinese text, no object ids.

Hope that helps.

**Comment by bilhackmac** [comment]
Ok thx, that's work great, I really missed this script.

I had effectively thought of a hash (with only numeric output) but I don't even known murmur3.

And just by curiosity, where do you find seed for mm3 ?

**Comment by xforce** [comment]
> Ok thx, that's work great, I really missed this script.
> 
> I had effectively thought of a hash (with only numeric output) but I don't even known murmur3.
> 
> And just by curiosity, where do you find seed for mm3 ?

Somewhere in the game code.

**Comment by bilhackmac** [comment]
Ok. That out of my range.

Thanks a lot
