### ISSUE TITLE
Data file url broken

### ISSUE THREAD

**Issue by egoist-sx** [xforce/eve-echoes-tools#4]
It seems data url hosted aws is broken. Would you please update data url or give some suggestion on how to create xapk from apk and obb files?

**Comment by xforce** [comment]
NetEase has requested for the aws link to be taken down.

xapk files can be found on sites like apkpure
https://apkpure.com/eve-echoes/com.netease.eve.en

**Comment by egoist-sx** [comment]
Thanks!
