### ISSUE TITLE
Docker and fsd2json

### ISSUE THREAD

**Issue by ajeroth** [xforce/eve-echoes-tools#5]
When I run your docker with the command:
docker run -v$(pwd):/data cookiemagic/evee-tools fsd2json xx.sd

I recieve the following error:
standard_init_linux.go:211: exec user process cause "exec format error"

looking that up, there may be a .sh file somewhere that doesn't lead with #!/bin/bash

**Comment by xforce** [comment]
The docker image is currently not designed to run the individual tools directly.
The only supported way to call it is currently to use `dump_static` and supply the xapk file.
See `https://github.com/xforce/eve-echoes-tools/blob/main/docker/cmd.sh` on how that is handled.

PR to add supported for other things is welcome :)

**Comment by xforce** [comment]
Regardless, I just tested with the latest docker image and no command, not even the one you posted, throws an error?
Could it be that you are running an outdated version? Maybe try a `docker pull cookiemagic/evee-tools`?

**Comment by xforce** [comment]
What is the system you are trying to run this on?

**Comment by ajeroth** [comment]
Thanks for the response 👍 
Pulling in docker just returned that I'm using the most current version.

I'm thinking it's my system at this point.  I'm running docker on a raspberry pi 4+, running stretch.  

In any case, I wasn't able to compile and run the fsd2json, and I was trying everything I could think of.  Cargo complains about the .toml files.
Cloning and running "cargo install --path ." in the eve-echoes-tools directory gets:
error: found a virtual manifest at `/xx/eve-echoes-tools/Cargo.toml` instead of a package manifest

Running "cargo install --path ." in the fsd2sjon folder gets:
error: failed to read `/xx/eve-echoes-tools/neox-tools/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

So I cloned your neox-tools into the eve-echoes-tools/neox-tools, reran cargo and I got:
error: failed to compile `fsd2json v0.1.0 (/xx/eve-echoes-tools/fsd2json)`, intermediate artifacts can be found at `/xx/eve-echoes-tools/target`

Caused by:
  failed to parse lock file at: /xx/eve-echoes-tools/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`

I even installed rust and tried compiling/installing your main.rs file, and got a ton of errors.

Again, I'm thinking this is me trying to run this on raspbian . . .

**Comment by xforce** [comment]
Ah yes. So the docker image won't work on a PI, because it is built as x86_64 not arm.

I have no arm machines myself.
But installation is supposed to work after doing a recursive clone and then running `cargo install --path fsd2json`
Not sure about the lock error. Maybe try deleting it and then running install or build again?
Of course, all this is developed on x86_64 so may just not work on ARM.

Maybe I can find a way to setup an emulated arm environment at some point this week and see if I can make it work.

**Comment by ajeroth** [comment]
Deleting the .lock file fixed the cargo errors, now cargo was able to run and almost compiled everything.

In the middle of compiling all of the libraries, one got an error:
   Compiling unicode-width v0.1.8
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.0/src/lib.rs:31:1
   |
31 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^

**Comment by xforce** [comment]
What is the rust version you are using?
alloc has been stabilized last year, so that error is a bit surprising.

**Comment by ajeroth** [comment]
Raspbian is a little slow on the updates:

Apt reports:
Version: 1.34.2+dfsg1-1+rpi1

rustc -V:
rustc 1.34.2

**Comment by ajeroth** [comment]
I rustedup and I only recieved a warning during compilation.  fsd2json is compiles, in my path and has successfully processed an .sd file.  Thanks a ton for your help!

I have included the warning FYI:
   Compiling fsd2json v0.1.0 (/xx/eve-echoes-tools/fsd2json)
warning: use of deprecated item 'simple_logger::init_with_level': Please use the Builder pattern instead.
   --> fsd2json/src/main.rs:868:5
    |
868 |     simple_logger::init_with_level(log::Level::Info).unwrap();
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

**Comment by xforce** [comment]
Yea, didn't get to fixing that yet. Only a warning so not a big deal.

Glad that it is all working for you now. Have fun.

**Comment by xforce** [comment]
I actually did investigate this a bit more, and now have a setup where I can build arm images on my x86 machine :open_mouth: 
Will push a multi-arch (x86 + arm64) image tomorrow :smile:
