### ISSUE TITLE
failed to compile `fsd2json v0.1.0 (/app/fsd2json)` while building docker image

### ISSUE THREAD

**Issue by Eve-Parser** [xforce/eve-echoes-tools#7]
Hi 
First thanks for your great work.
I used your prior version of the container, but since your last update  I can not manage to build the image  anymore.

I have an issue while building the docker image.
It failed to compile `fsd2json v0.1.0 (/app/fsd2json)`

Here are my errors: 

> Step 10/22 : RUN cargo install --path fsd2json --root /usr/local/
 ---> Running in f3dd406b601a
  Installing fsd2json v0.1.0 (/app/fsd2json)
    Updating crates.io index
warning: spurious network error (2 tries remaining): failed to resolve address for github.com: Name does not resolve; class=Net (12)
warning: spurious network error (1 tries remaining): failed to resolve address for github.com: Name does not resolve; class=Net (12)
error: failed to compile 'fsd2json v0.1.0 (/app/fsd2json)', intermediate artifacts can be found at '/app/target'
Caused by:
  failed to get 'byteorder' as a dependency of package 'fsd2json v0.1.0 (/app/fsd2json)'
Caused by:
  failed to load source for dependency 'byteorder'
Caused by:
  Unable to update registry 'https://github.com/rust-lang/crates.io-index'
Caused by:
  failed to fetch 'https://github.com/rust-lang/crates.io-index'
Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary 'net.git-fetch-with-cli' may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
Caused by:
  failed to resolve address for github.com: Name does not resolve; class=Net (12)

I have tried  to change the Dockerfile with RUN CARGO_NET_GIT_FETCH_WITH_CLI=true cargo install --path fsd2json --root /usr/local/ .... without success... now I have:

> ---> Running in 9bf64c8a4944
  Installing fsd2json v0.1.0 (/app/fsd2json)
    Updating crates.io index
error: failed to compile 'fsd2json v0.1.0 (/app/fsd2json)', intermediate artifacts can be found at '/app/target'
Caused by:
  failed to get 'byteorder' as a dependency of package `fsd2json v0.1.0 (/app/fsd2json)'
Caused by:
  failed to load source for dependency 'byteorder'
Caused by:
  Unable to update registry 'https://github.com/rust-lang/crates.io-index'
Caused by:
  failed to fetch 'https://github.com/rust-lang/crates.io-index'
Caused by:
  could not execute process 'git fetch --force --update-head-ok 'https://github.com/rust-lang/crates.io-index' 'refs/heads/master:refs/remotes/origin/master'' (never executed)
Caused by:
  No such file or directory (os error 2)

Am I doing something wrong ?

Thanks in advance for your help

Regards

**Comment by xforce** [comment]
This looks like network errors, are you running some kind of proxy/vpn?
This seems to be using the docker image, can you ping if you run a plain old ubuntu docker image or download something with wget/curl? if no, then something with your docker setup and networking seems to be broken.

**Comment by Eve-Parser** [comment]
Thanks for your quick reply
No I am not running a proxy/vpn
...
something is really weird here: 

> Step 10/23 : RUN ping -c 3 google.com
 ---> Running in ba809dcb9276
PING google.com (216.58.213.142): 56 data bytes
64 bytes from 216.58.213.142: seq=0 ttl=37 time=6.764 ms
64 bytes from 216.58.213.142: seq=1 ttl=37 time=12.722 ms
64 bytes from 216.58.213.142: seq=2 ttl=37 time=10.322 ms

But

> Step 10/23 : RUN ping -c 3 github.com
 ---> Running in 1243f43bf50c
ping: bad address 'github.com'

**Comment by Eve-Parser** [comment]
Fixed it by adding --add-host 'github.com:140.82.121.3' to the image build 

Thanks a lot for you help, you pointed me to the right direction

**Comment by Eve-Parser** [comment]
btw I also had to git clone https://github.com/xforce/neox-tools as:

Step 7/21 : ADD neox-tools/src /app/neox-tools/src
ADD failed: stat /var/lib/docker/tmp/docker-builder063067849/neox-tools/src: no such file or directory

**Comment by xforce** [comment]
Yep, a few things are currently broken with regards to the repo, I had to change things, still a bit WIP.
There is a pre-built image available, which can be used directly, in case you run into some issues.
Will hopefully have the changed things finished later today.
