### ISSUE TITLE
dump_static_data.py returned non-zero exit status 1

### ISSUE THREAD

**Issue by Eve-Parser** [xforce/eve-echoes-tools#8]
Hi

I now have my image:

`$ docker images`

> REPOSITORY      TAG      IMAGE ID    CREATED      SIZE
cookiemagic/evee-tools  latest    3a77af58e520    13 minutes ago  85.6MB
evee-tools        latest    21f8d10fe6cf    4 hours ago    1.25GB

evee-tools (old version) works fine
but cookiemagic/evee-tools (new version) crashes (on the same eve.xapk, in a different folder).

Here are errors I receive: 

`$ docker run --rm -v$(pwd):/data cookiemagic/evee-tools dump_static /data/eve.xapk /data/staticdata`
2020-10-06 11:35:55,964 WARN  [npktool] Handle unknown special case! Changing field 28
2020-10-06 11:35:58,535 INFO  [npktool] Done.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "scripts/dump_static_data.py", line 158, in dump_script_unpack
    return dump_script(*args)
  File "scripts/dump_static_data.py", line 89, in dump_script
    script_redirect_out = execute_stdout([sys.executable, "neox-tools/scripts/script_redirect.py", os.path.join(script_extract_dir,
  File "scripts/dump_static_data.py", line 75, in execute_stdout
    raise e
  File "scripts/dump_static_data.py", line 70, in execute_stdout
    output = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'neox-tools/scripts/script_redirect.py', '/tmp/tmp200xj8ot/unknown_file_name/E302128602225F51.nxs']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/dump_static_data.py", line 344, in <module>
    dump_scripts(apk)
  File "scripts/dump_static_data.py", line 183, in dump_scripts
    pool.map_async(dump_script_unpack, files).get(9999999)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'neox-tools/scripts/script_redirect.py', '/tmp/tmp200xj8ot/unknown_file_name/E302128602225F51.nxs']' returned non-zero exit status 1.
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'
b'Traceback (most recent call last):\n  File "neox-tools/scripts/script_redirect.py", line 45, in <module>\n    main()\n  File "neox-tools/scripts/script_redirect.py", line 36, in main\n    data = script_redirect.unnpk(open(input_file, "rb").read())\nAttributeError: module \'script_redirect\' has no attribute \'unnpk\'\n'

**Comment by xforce** [comment]
Yes, sorry about that. Had to change a few things with force-pushes in the other repo, so there is currently an incompatibility. Was on vacation last week, and busy with other things on the weekend so didn't get to finish everything.
Hopefully I can get it done later today.
For now best to use the prebuilt docker image on docker hub, I guess. that one _should_ work fine still.

If that is not an option, manually finding the correct script, which will remain a manual step and putting it right next to `script_redirect.py` as `script_redirect_plug.py` will make the current code work. (which is supported in the code, I just pushed, wasn't before).
That script handles decrypting the netease script files, which I cannot provide as-is to comply with local laws.
You can find a few already compatible ones on the internet. Search for `neox unnpk` on google and you will find some repos with Chinese Text in the title, those have a compatible script.

**Comment by Eve-Parser** [comment]
Thank you for your quick answer :)

**Comment by xforce** [comment]
Sure thing, a bit of unfortunate timing with me breaking things to be safe for me, and you trying to use it this way. Will get it in a slightly better state soon.
